### ISSUE TITLE
Compilation Error: stg_facebook_ads__carousel_media_url_tags

### ISSUE THREAD

**Issue by jordanfowler** [fivetran/dbt_ad_reporting#13]
While running v0.2.1 I can't seem to get past this error:

`
$ dbt test
Running with dbt=0.19.1
Encountered an error:
Compilation Error
  dbt found two resources with the name "stg_facebook_ads__carousel_media_url_tags". Since these resources have the same name,
  dbt will be unable to find the correct resource when ref("stg_facebook_ads__carousel_media_url_tags") is used. To fix this,
  change the name of one of these resources:
  - model.facebook_ads_creative_history.stg_facebook_ads__carousel_media_url_tags (models/redshift/stg_facebook_ads__carousel_media_url_tags.sql)
  - model.facebook_ads_creative_history.stg_facebook_ads__carousel_media_url_tags (models/spark/stg_facebook_ads__carousel_media_url_tags.sql)
`

**Comment by DylanBaker** [comment]
Hi Jordan. That's odd. In theory, that should be handled by these lines: https://github.com/fivetran/dbt_facebook_ads_creative_history/blob/master/dbt_project.yml#L8-L19

Could you look in `/dbt_modules/facebook_ads_creative_history/dbt_project.yml` to see if those lines are present?

**Comment by jordanfowler** [comment]
Hi @DylanBaker, thanks for getting back to me. Those lines are present.

**Comment by jordanfowler** [comment]
For reference, here's my `profiles.yml`:

```
default:
  target: dev
  outputs:
    dev:
      type: redshift
      host: ****
      user: ****
      password: ****
      port: 5439
      dbname: dev
      schema: ****
      threads: 4
```

**Comment by DylanBaker** [comment]
Could you try, if you haven't already, deleting your `dbt_modules` directory and re-running `dbt deps`? It might be that there's a stale version of a package in there.

If it's not that, I'll give some thought to what some further tests to debug could be.

Thanks!

**Comment by jordanfowler** [comment]
@DylanBaker I've definitely tried that, here's the dependency `dbt_project.yml` in question (in my `dbt_modules` directory):

```

name: 'facebook_ads_creative_history'
version: '0.2.1'
config-version: 2

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
  facebook_ads_creative_history:
    +schema: facebook_ads_creative_history
    +materialized: table
    bigquery:
      enabled: "{{ target.type == 'bigquery' | as_bool() }}"
    redshift:
      enabled: "{{ target.type == 'redshift' | as_bool() }}"
    snowflake:
      enabled: "{{ target.type == 'snowflake' | as_bool() }}"
    spark:
      enabled: "{{ target.type == 'spark' | as_bool() }}"

vars:
  dbt_utils_dispatch_list: ['spark_utils', 'fivetran_utils']
  fivetran_utils_dispatch_list: ['spark_utils']
```

**Comment by DylanBaker** [comment]
Thanks @jordanfowler. That all looks correct to me. I'd like to try to pinpoint whether it's the Facebook ads package, or the usage of the facebook ads package by the ad reporting package somehow. 

Could you try deleting your dbt_modules and just reinstalling the facebook package? I'd be interested to see whether the error persists.

**Comment by fivetran-kristin** [comment]
hey @jordanfowler just wanted to follow up here.  Were you able to try deleting your dbt_modules and just reinstalling the facebook package?

**Comment by darreldonnelly** [comment]
@DylanBaker / @fivetran-kristin I'm also hitting this issue on a fresh clone except i get a conflict between snowflake and bigquery (I'm using snowflake). 
I tried removing and disabling all packages except facebook and only enabled `facebook_ads_creative_history` model (also tried only the three facebook models enabled)

```$ dbt run
Running with dbt=0.19.1
Encountered an error:
Compilation Error
  dbt found two resources with the name "stg_facebook_ads__carousel_media". Since these resources have the same name,
  dbt will be unable to find the correct resource when ref("stg_facebook_ads__carousel_media") is used. To fix this,
  change the name of one of these resources:
  - model.facebook_ads_creative_history.stg_facebook_ads__carousel_media (models/snowflake/stg_facebook_ads__carousel_media.sql)
  - model.facebook_ads_creative_history.stg_facebook_ads__carousel_media (models/bigquery/stg_facebook_ads__carousel_media.sql)```

**Comment by fivetran-joemarkiewicz** [comment]
Hi All!

I wanted to swing in here as I encountered a very similar dbt error the other day using this package and found the result was caused by me overriding the models config within the root `dbt_project.yml`, which then removed the boolean config for the various databases (which you see within the `dbt_project.yml` for the `facebook_ads_creative_history` package).

@darreldonnelly would you be able to provide your models config that is used within your root `dbt_project.yml`? My suspicion is that you may have included the below:
```yml
models:
  facebook_ads:
    enabled: true
  facebook_ads_source:
    enabled: true
  facebook_ads_creative_history:
    enabled: true
```

By default these are set to `true` and do not need to be set within your root `dbt_project.yml`, they only need to be set if you are trying to disable them. I am not sure why setting them to `true` overrides the boolean model config for the databases, but it seems to do just that. If you do indeed have this config, would you be able to try and remove it and run again as this may help resolve the error you showed in the above comments. 

Thank you!

**Comment by darreldonnelly** [comment]
Thanks @fivetran-joemarkiewicz ! This has indeed resolved my issue. I can also confirm that the schema override functionality still works in that block e.g. 

```yaml 
models:
  facebook_ads_source:
    +schema: facebook_ads_sourcetest
```
Appreciated
