### ISSUE TITLE
BUG - Failed unique test results for google ads source

### ISSUE THREAD

**Issue by oscarlukersmithsc** [fivetran/dbt_ad_reporting#28]
**Are you a current Fivetran customer?** 
Oscar Lukersmith at SafetyCulture

**Describe the bug**
We have started receiving failed test results for `unique_stg_google_ads__final_url_performance_final_url_performance_id`

```
Completed with 1 error and 0 warnings:

Failure in test unique_stg_google_ads__final_url_performance_final_url_performance_id (models/stg_google_ads.yml)
  Got 81684 results, configured to fail if != 0

  compiled SQL at target/compiled/google_ads_source/models/stg_google_ads.yml/schema_test/unique_stg_google_ads__final_u_3521f620458941ffffe40e69979b6e54.sql
```

The unique key doesn't appear to be unique in the underlying table
![image](https://user-images.githubusercontent.com/54382162/137561457-6f61305a-fc07-4a19-a27a-c7b124f6b976.png)

**Steps to reproduce**
N/A

**Expected behavior**
For the test to pass, and to have a unique key

**Project variables configuration**
```

name: 'analytics'
version: '2.0.0'
config-version: 2


profile: 'default'


source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  'dbt_date:time_zone': 'UTC'
  ad_reporting__pinterest_enabled: False
  ad_reporting__microsoft_ads_enabled: True
  ad_reporting__linkedin_ads_enabled: True
  ad_reporting__google_ads_enabled: True
  ad_reporting__twitter_ads_enabled: False
  ad_reporting__facebook_ads_enabled: True
  ad_reporting__snapchat_ads_enabled: False

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"



models:
  +pre-hook: "{{ alter_quota(1000) }}"
  +post-hook: "{{ grant_permissions('select', 'ia', 'yes') }}"
  +bind: false
  analytics:
    exposure:
      tableau:
        +post-hook: "{{ grant_permissions('select', 'tableau') }}"
  
  # disable both pinterest models if not using pinterest ads
  pinterest:
    enabled: false
    
  pinterest_source:
    enabled: false

  # disable both twitter ads models if not using twitter ads
  twitter_ads:
    enabled: false
   
  twitter_ads_source:
    enabled: false
    

  # disable both snapchat ads models if not using snapchat ads
  snapchat_ads:
    enabled: false
    
  snapchat_ads_source:
    enabled: false
    

  # disable both google ads models if not using google ads
  linkedin:
    enabled: true
  linkedin_source:
    enabled: true
   
  
  google_ads:
    enabled: true
  google_ads_source:
    enabled: true
  
  microsoft_ads:
    enabled: true
  microsoft_ads_source:
    enabled: true

```

**Warehouse**

- [ ] BigQuery
- [X] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**

**Screenshots**

**Please indicate the level of urgency** 
High Urgency

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-kristin** [comment]
@oscarlukersmithsc thanks for submitting this bug. Quick question for you - which version of the package are you currently using (from your packages.yml file)?

**Comment by oscarlukersmithsc** [comment]
I've just realised this is not the latest version.

**Comment by fivetran-kristin** [comment]
Do you see this error if you run `dbt run --full-refresh`?

**Comment by oscarlukersmithsc** [comment]
I have added it like this, but I still get the same error. I agree it seems to be getting confused between adwords and google_ads 
```
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  'dbt_date:time_zone': 'UTC'
  ad_reporting__pinterest_enabled: False
  ad_reporting__microsoft_ads_enabled: True
  ad_reporting__linkedin_ads_enabled: True
  ad_reporting__google_ads_enabled: True
  ad_reporting__twitter_ads_enabled: False
  ad_reporting__facebook_ads_enabled: True
  ad_reporting__snapchat_ads_enabled: False
  api_source: google_ads  ## adwords by default
```
