### ISSUE TITLE
BUG - [your bug title here]

### ISSUE THREAD

**Issue by simon-tarr** [fivetran/dbt_ad_reporting#43]
**Are you a current Fivetran customer?** 
Yes. TOCC.

**Describe the bug**
You recently updated the `dbt_ad_reporting` package to v0.6.0. Installation instructions are:
```
packages:
  - package: fivetran/ad_reporting
    version: [">=0.6.0", "<0.7.0"]
```
Having added this to my `packages.yml` file and running `dbt deps` I get the following error:

```
12:37:04  Running with dbt=1.0.0
12:37:10  Encountered an error:
Version error for package dbt-labs/dbt_utils: Could not find a satisfactory version from options: ['=0.8.0', '>=0.6.2', '<0.8.0']
```

Is the above error an issue with my `packages.yml` file or is there some sort of dependency error in Fivetran's dbt packages?

**Expected behavior**
I expect ad_reporting to update to v0.6.0

**Package Version**

```yml
packages:
  - package: fivetran/ad_reporting
    version: [">=0.6.0", "<0.7.0"]
  - package: fivetran/zendesk_source
    version: [">=0.4.0", "<0.5.0"]
  - package: fivetran/zendesk
    version: 0.7.0
  - package: dbt-labs/codegen
    version: 0.4.0
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Comment by fivetran-joemarkiewicz** [comment]
Hi @simon-tarr thanks so much for creating this issue and I am sorry to see you are experiencing the dependency error.

Looking at your `packages.yml` it seems you are using versions of packages that install different versions of dbt-utils. It actually seems that all your other packages (besides the new ad_reporting package) use the older `[">=0.7.0", "<0.8.0"]` range for dbt-utils. While the ad_reporting uses the latest `[">=0.8.0", "<0.9.0"]` range. 

I would recommend either upgrading all your other packages to their latest versions so they have compatible dbt-util versions for dbt v1. Or downgrading your ad_reporting package. 

Please note, if you end up upgrading your zendesk package to the latest then you will want to use our pre-release version for dbt v1 compatibility for the time being.
```yml
packages:
  - package: fivetran/zendesk
    version: 0.8.0-b1
```
