### ISSUE TITLE
[Bug] Turning off Apple ads package still runs source freshness

### ISSUE THREAD

**Issue by nszoni** [fivetran/dbt_ad_reporting#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Turning off the usage of Apple ads platform as stated in the package README doesn't actually turn off source freshness tests for the models, although the config is conditioned on the variable set to `False`

```yml
sources:
  - name: apple_search_ads
    schema: "{{ var('apple_search_ads_schema', 'apple_search_ads') }}"
    database: "{% if target.type != 'spark'%}{{ var('apple_search_ads_database', target.database) }}{% endif %}"

    loader: Fivetran
    loaded_at_field: _fivetran_synced

    freshness: 
      warn_after: {count: 48, period: hour}
      error_after: {count: 168, period: hour}

    config:
      enabled: "{{ var('ad_reporting__apple_search_ads_enabled', true) }}"
```

### Relevant error log or model output

```shell
15:27:40  1 of 36 START freshness of apple_search_ads.search_term_report ................. [RUN]
15:27:41  1 of 36 ERROR freshness of apple_search_ads.search_term_report ................. [ERROR in 0.68s]

15:27:50  Runtime Error in source search_term_report (models/src_apple_search_ads.yml)
15:27:50    404 Not found: Dataset xxxxx:apple_search_ads was not found in location US
15:27:50    
15:27:50    (job ID: b656a397-d0c4-4f36-b651-898edfaf03cb)
15:27:50  
15:27:50  
15:27:50  Done.
```

### Expected behavior

I would expect dbt not running source freshness tests for Apple because we are not creating those.

### dbt Project configurations

```yml
vars:
  ad_reporting__apple_search_ads_enabled: False
  ad_reporting__pinterest_ads_enabled: false
  ad_reporting__linkedin_ads_enabled: false
  ad_reporting__twitter_ads_enabled: false
  ad_reporting__snapchat_ads_enabled: false
  ad_reporting__tiktok_ads_enabled: false

  apple_search_ads__using_search_terms: False
```

### Package versions

```yml
packages:
  - package: calogica/dbt_date
    version: [">=0.5.0", "<0.6.0"]
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/codegen
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/shopify
    version: [">=0.6.0", "<0.7.0"]
  - package: fivetran/google_ads
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/google_ads_source
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/microsoft_ads
    version: [">=0.5.0", "<0.6.0"]
  - package: fivetran/facebook_ads
    version: [">=0.5.0", "<0.6.0"]
  - package: fivetran/ad_reporting
    version: [">=1.0.0", "<1.1.0"]
  - package: calogica/dbt_expectations
    version: [">=0.5.0", "<0.6.0"]
# - package: fivetran/klaviyo
#   version: [">=0.4.0", "<0.5.0"]
  - package: dbt-labs/segment
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/instagram_business
    version: [">=0.1.0", "<0.2.0"]
  - package: fivetran/fivetran_utils
    version: [">=0.3.0", "<0.4.0"]
  - package: dbt-labs/metrics
    version: [">=0.3.0", "<0.4.0"]

```

### What database are you using dbt with?

bigquery

### dbt Version

```bash
❯ dbt --version
Core:
  - installed: 1.2.0
  - latest:    1.3.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.2.0 - Update available!
 ```

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
