### ISSUE TITLE
[Bug] Add correct variable name (passthrough metric) in `ad_reporting__url_report`

### ISSUE THREAD

**Issue by aleix-cd** [fivetran/dbt_ad_reporting#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When developing https://github.com/fivetran/dbt_ad_reporting/pull/84, I forgot to change the variable name in `ad_reporting__url_report`. 

We decided, together with Joe, that we would keep the same variable name for both Ad and URL reports, but I never changed the variable name in the URL report (see `models/ad_reporting__url_report.sql`):
```
{{ fivetran_utils.persist_pass_through_columns(pass_through_variable='ad_reporting__url_passthrough_metrics', transform = 'sum') }}
```

Instead, it should be:
```
{{ fivetran_utils.persist_pass_through_columns(pass_through_variable='ad_reporting__ad_passthrough_metrics', transform = 'sum') }}
```

### Expected behavior

I would expect, when using the `ad_reporting__ad_passthrough_metrics` variable, for the model `ad_reporting__url_report` to include any metric specified in that variable when compiled.

### dbt Project configurations

```
google_ads__ad_stats_passthrough_metrics:
    - name: conversions
linkedin_ads__creative_passthrough_metrics:
    - name: external_website_conversions
      alias: conversions
microsoft_ads__ad_passthrough_metrics:
    - name: conversions
facebook_ads__basic_ad_passthrough_metrics:
    - name: conversions
ad_reporting__ad_passthrough_metrics:
    - name: conversions
```

### Package versions

```
- package: fivetran/ad_reporting
  version: [">=1.4.0", "<1.5.0"]
```

### What database are you using dbt with?

snowflake

### dbt Version

v1.5.2

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
